#!/usr/bin/env python3
"""Build the Worker 4 legacy-prompt campaign matrix.

The matrix is the frozen machine-readable contract for the 15 Native
legacy-prompt treatment routes: one record per route (config, backend,
dataset, modality, folds, run root, prompt hashes) plus one record per training
fit (route, seed, fold, deterministic run name). It is built only from the
tracked treatment configs generated by
``scripts/build_qwen3_legacy_prompt_configs.py``; default matrices and other
lanes are never consulted.

Layout:

- DAIC runs fold 0 only; D3TEC, Androids, CMDC and pooled Turkish run folds 0-4.
- Training seeds 7, 1337 and 2024; split seed 1337; head seed 1337.
- 15 routes x 21 folds x 3 seeds = 189 fits (63 text_only, 126 audio).

``--check`` fails closed when the route set, fold sets, counts, run roots or
config identities drift from this contract.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.build_qwen3_legacy_prompt_configs import (
    CAMPAIGN,
    DATASET_DIRS,
    MODALITIES,
    MARKER,
    NON_TURKISH,
    control_name,
    treatment_name,
)
from src.data.prompt_context import resolve_system_prompt

MAIN = ROOT / "configs/main"
SCHEMA_VERSION = "audiollm.qwen3_legacy_prompt_matrix.v1"

GROUP_ID = "qwen3-legacy-prompt-20261008"
LANE = "feat-qwen3-legacy-prompt-20261008"
BASELINE_SHA = "35f2d91e55acf6f21cd9e0f82590a56648180044"
TRAINING_SEEDS = (7, 1337, 2024)
SPLIT_SEED = 1337
HEAD_SEED = 1337
FOLDS_BY_DATASET = {
    "daic": (0,),
    "d3tec": (0, 1, 2, 3, 4),
    "androids": (0, 1, 2, 3, 4),
    "cmdc": (0, 1, 2, 3, 4),
    "turkish": (0, 1, 2, 3, 4),
}

# Verified backend-specific activation scripts. Submissions must pass these
# explicitly; the worker default (qwen_mn5_rebuilt) lacks the Qwen3-Omni
# processor class and is never valid for this campaign.
ENVIRONMENTS = {
    "qwen38": "/gpfs/projects/etur92/ozu647717/venvs/qwen38_fsdp_fastpath_20260921/bin/activate",
    "qwen3omni": "/gpfs/projects/etur92/ozu647717/venvs/qwen3omni/bin/activate",
}


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def route_record(dataset: str, modality: str) -> dict[str, Any]:
    config_path = MAIN / treatment_name(dataset, modality)
    config = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    system_prompt = resolve_system_prompt(config)
    user_template = str(config["prompt"]["user_template"])
    route_id = f"{DATASET_DIRS[dataset]}_{modality}"
    return {
        "route_id": route_id,
        "dataset": config["dataset"],
        "dataset_dir": DATASET_DIRS[dataset],
        "modality": modality,
        "backend": config.get("model_backend"),
        "config": str(config_path.relative_to(ROOT)),
        "control_config": str((MAIN / control_name(dataset, modality)).relative_to(ROOT)),
        "config_sha256": sha256_file(config_path),
        "recipe_id": config["recipe_id"],
        "folds": list(FOLDS_BY_DATASET[dataset]),
        "run_root": config["output_dirs"]["run_root"],
        "prompt_system_sha256": sha256_text(system_prompt),
        "prompt_user_template_sha256": sha256_text(user_template),
    }


def build_matrix() -> dict[str, Any]:
    routes = [
        route_record(dataset, modality)
        for dataset in (*NON_TURKISH, "turkish")
        for modality in MODALITIES
    ]
    fits: list[dict[str, Any]] = []
    for route in routes:
        for seed in TRAINING_SEEDS:
            for fold in route["folds"]:
                fits.append(
                    {
                        "key": f"{route['route_id']}|s{seed}|f{fold}",
                        "route_id": route["route_id"],
                        "dataset": route["dataset"],
                        "dataset_dir": route["dataset_dir"],
                        "modality": route["modality"],
                        "seed": int(seed),
                        "fold": int(fold),
                        "run_name": f"q3lp_{route['route_id']}_s{seed}_f{fold}",
                        "config": route["config"],
                        "campaign": CAMPAIGN,
                    }
                )
    text_fits = sum(1 for fit in fits if fit["modality"] == "text_only")
    return {
        "schema_version": SCHEMA_VERSION,
        "campaign": CAMPAIGN,
        "group_id": GROUP_ID,
        "lane": LANE,
        "baseline_sha": BASELINE_SHA,
        "training_seeds": list(TRAINING_SEEDS),
        "split_seed": SPLIT_SEED,
        "head_seed": HEAD_SEED,
        "routes": routes,
        "fits": fits,
        "summary": {
            "routes": len(routes),
            "fits": len(fits),
            "text_fits": text_fits,
            "audio_fits": len(fits) - text_fits,
        },
    }


def check_matrix(matrix: dict[str, Any]) -> list[str]:
    failures: list[str] = []
    routes, fits = matrix["routes"], matrix["fits"]
    if len(routes) != 15:
        failures.append(f"expected 15 routes, found {len(routes)}")
    if len(fits) != 189:
        failures.append(f"expected 189 fits, found {len(fits)}")
    if matrix["summary"] != {
        "routes": len(routes),
        "fits": len(fits),
        "text_fits": sum(1 for fit in fits if fit["modality"] == "text_only"),
        "audio_fits": sum(1 for fit in fits if fit["modality"] != "text_only"),
    }:
        failures.append("summary does not match the route/fit records")
    seen_keys: set[str] = set()
    seen_runs: set[str] = set()
    for route in routes:
        config_path = ROOT / route["config"]
        if MARKER not in config_path.name:
            failures.append(f"route config is not a treatment file: {route['config']}")
        if not config_path.is_file():
            failures.append(f"missing route config: {route['config']}")
            continue
        if sha256_file(config_path) != route["config_sha256"]:
            failures.append(f"config hash drift: {route['config']}")
        config = yaml.safe_load(config_path.read_text(encoding="utf-8"))
        expected_root = (
            "${PROJECT_ROOT}/output_model/"
            f"{CAMPAIGN}/{route['modality']}/{route['dataset_dir']}"
        )
        if config["output_dirs"]["run_root"] != expected_root:
            failures.append(f"run root drift: {route['config']}")
        if route["route_id"] != f"{route['dataset_dir']}_{route['modality']}":
            failures.append(f"route id drift: {route['route_id']}")
        if sha256_text(resolve_system_prompt(config)) != route["prompt_system_sha256"]:
            failures.append(f"system prompt hash drift: {route['config']}")
        if sha256_text(str(config["prompt"]["user_template"])) != route["prompt_user_template_sha256"]:
            failures.append(f"user template hash drift: {route['config']}")
    for fit in fits:
        if fit["key"] in seen_keys:
            failures.append(f"duplicate fit key: {fit['key']}")
        seen_keys.add(fit["key"])
        if fit["run_name"] in seen_runs:
            failures.append(f"duplicate run name: {fit['run_name']}")
        seen_runs.add(fit["run_name"])
        route = next((r for r in routes if r["route_id"] == fit["route_id"]), None)
        if route is None:
            failures.append(f"fit without route: {fit['key']}")
            continue
        if fit["fold"] not in route["folds"]:
            failures.append(f"fold outside the route contract: {fit['key']}")
    if len({route["route_id"] for route in routes}) != 15:
        failures.append("route ids are not unique")
    return failures


def build_production_graph(matrix: dict[str, Any], matrix_sha256: str) -> dict[str, Any]:
    fits = matrix["fits"]
    fit_count = len(fits)
    wave_size = 40
    waves = [
        {
            "wave": index + 1,
            "fits": min(wave_size, fit_count - index * wave_size),
            "scheduler_jobs": 2 * min(wave_size, fit_count - index * wave_size),
        }
        for index in range((fit_count + wave_size - 1) // wave_size)
    ]
    return {
        "schema_version": "audiollm.qwen3_legacy_prompt_production_graph.v1",
        "campaign": CAMPAIGN,
        "lane": LANE,
        "baseline_sha": BASELINE_SHA,
        "matrix_sha256": matrix_sha256,
        "core_training": {
            "train_jobs": fit_count,
            "eval_jobs": fit_count,
            "total_scheduler_jobs": 2 * fit_count,
            "per_fit_job_keys": ["train", "best_eval"],
            "note": (
                "best_eval depends on train; text shape 1 node x 4 GPUs accumulation 32, "
                "audio shape 2 nodes x 4 GPUs accumulation 16, effective global batch 128"
            ),
        },
        "downstream_heads": {
            "extract_jobs": fit_count,
            "classifier_jobs": fit_count,
            "total_scheduler_jobs": 2 * fit_count,
            "runner": "tools/qwen3_heads_dispatch.py",
            "per_key_variants": ["logreg_raw", "xgb_raw"],
            "head_seed": HEAD_SEED,
            "note": "issued per parent key after each treatment training attempt completes",
        },
        "cpu_aux": {
            "manifest_builds": 4,
            "note": (
                "D3TEC/Androids/DAIC/CMDC build manifests in their first training job; "
                "Turkish pooled uses the prebuilt verified manifest"
            ),
        },
        "smokes_submitted": {"chains": 2, "jobs": 4, "reportable": False},
        "slot_policy": {
            "lane_cap_nonterminal": 80,
            "campaign_cap": 320,
            "user_stop_threshold": 350,
            "planned_wave_size_fits": wave_size,
            "refill_after_terminal": True,
            "no_peer_borrowing": True,
        },
        "environments": {
            "per_backend": ENVIRONMENTS,
            "note": (
                "every train and evaluation submission must pass --env-activate with the "
                "backend-specific path; the worker default qwen_mn5_rebuilt lacks "
                "Qwen3OmniMoeProcessor and is invalid for this campaign"
            ),
        },
        "planned_waves": waves,
        "total_new_base_fits": fit_count,
        "total_core_scheduler_jobs": 2 * fit_count,
        "total_with_downstream_scheduler_jobs": 4 * fit_count,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--emit-matrix",
        default=str(ROOT / "outputs" / CAMPAIGN / "matrix.json"),
    )
    parser.add_argument(
        "--emit-production-graph",
        default=str(ROOT / "outputs" / CAMPAIGN / "production_graph.json"),
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    matrix = build_matrix()
    failures = check_matrix(matrix)
    matrix_text = json.dumps(matrix, indent=2, sort_keys=False) + "\n"
    if args.emit_matrix:
        output = Path(args.emit_matrix)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(matrix_text, encoding="utf-8")
    if args.emit_production_graph:
        graph_path = Path(args.emit_production_graph)
        graph_path.parent.mkdir(parents=True, exist_ok=True)
        graph_path.write_text(
            json.dumps(
                build_production_graph(matrix, sha256_text(matrix_text)),
                indent=2,
                sort_keys=False,
            )
            + "\n",
            encoding="utf-8",
        )
    if failures:
        print("Legacy-prompt matrix check FAILED:")
        for failure in failures:
            print(f"- {failure}")
        return 1
    if args.check:
        print(
            "Legacy-prompt matrix is frozen: "
            f"{matrix['summary']['routes']} routes, {matrix['summary']['fits']} fits "
            f"({matrix['summary']['text_fits']} text, {matrix['summary']['audio_fits']} audio)."
        )
    else:
        print(f"Wrote matrix -> {args.emit_matrix} and graph -> {args.emit_production_graph}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
